stages:
  - test
  - build
  - security
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: d4rkghost47/python-app-gitlab-ci

# Job de pruebas unitarias con linting
test:
  image: python:3.9-slim
  stage: test
  script:
    # Linting
    - pip install flake8
    - flake8 app/ tests/ --exit-zero

    # Pruebas unitarias
    - pip install -r requirements.txt
    - pytest tests/ --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
    when: on_success

# Job para construir la imagen Docker
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    # Construir la imagen con etiqueta temporal
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .

    # Exportar la imagen como un archivo tar
    - docker save $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -o image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour # Limita la duración del artefacto

# Job para escaneo de la imagen Docker
docker_scan:
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  stage: security
  dependencies:
    - build
  script:
    # Asegurarse de que el archivo tar esté presente
    - ls -lh image.tar

    # Escanear la imagen desde el archivo tar
    - image --input image.tar --severity HIGH,CRITICAL

  artifacts:
    when: always

# Job para subir la imagen al registro
push:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  dependencies:
    - build
  script:
    # Importar la imagen desde el artefacto
    - docker load -i image.tar

    # Loguearse al registro
    - echo "dckr_pat_zwGUehrkDTtA3bg0V5os4pOj-qQ" | docker login -u "d4rkghost47" --password-stdin

    # Subir la imagen con ambas etiquetas
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

